name: learn_bloc
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "^3.0.0"

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_analytics: ^10.4.0
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.4.2
  # firebase_in_app_messaging: ^0.7.3+5
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.1
  http: ^1.1.0
  intl: ^0.19.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  uuid: ^4.3.3
  shorthand:
    path: /Users/chhunvirak/personal_project/packages/shorthand

  url_launcher: ^6.1.14
  # cloud_firestore: ^4.9.3
  table_calendar: ^3.0.9
  gap: ^3.0.1
  showcaseview: ^2.0.3
  vector_math: ^2.1.4
  get: ^4.6.6
  modal_bottom_sheet:
    path: /Users/chhunvirak/personal_project/packages/modal_bottom_sheet/modal_bottom_sheet
  flutter_hooks: ^0.20.4
  go_router: ^13.0.1
  dogs_core: ^9.0.1
  built_value: ^8.8.1
  built_collection: ^5.1.1
  app_links: ^6.1.1

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.8
  dogs_generator: ^5.1.2
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.2
  flutter_svg: ^2.0.9
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1

# Flutter Gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    # lottie: true

  assets:
    enabled: true

    outputs:
      class_name: MyAssets
      package_parameter_enabled: false
      # Assets.imagesChip
      # style: camel-case

      # Assets.images_chip
      # style: snake-case

      # Assets.images.chip (default style)
      # style: dot-delimiter

    # exclude:
    #   - assets/images/chip3/chip3.jpg
    #   - pictures/chip5.jpg
    #   - assets/flare/

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
